/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base;

public class App {
    public static void main(String[] args) {

        int porta = 1234; // Port ade conexão do servidor

        IO.println("..:: Servidor ::..");

        try(ServerSocket serverSocket = new ServerSocket(porta)){

            IO.println("Aguardando por conexões...");

            while(!Thread.currentThread().isInterrupted()) {
                Socket clientSocket = serverSocket.accept(); // Esperando IO
                Thread.ofVirtual().start(new AtenderClientes(clientSocket));
            }

        } catch (Exception e) {
            System.err.println("Erro: " + e);
        }
        //serverSocket.close(); -- Obrigação de fechar a porta depois de terminada a conexão
    }
}
