/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base;

public class App {
    public static void main(String[] args) {

        int porta = 1234; // Port ade conexão do servidor

        IO.println("..:: Servidor ::..");

        try(ServerSocket serverSocket = new ServerSocket(porta)){

            IO.println("Aguardando por conexões...");

            Socket clientSocket = serverSocket.accept();
            //Abaixo dessa linha só sera executado após a conexão de um cliente

            var enderecoCliente = clientSocket.getInetAddress().getHostAddress();
            var portaCliente = clientSocket.getPort();

            System.out.printf("Cliente conectado: %s:%d%n", enderecoCliente, portaCliente);

            // Estabelecimentos de fluxos de entrada de saida
            var reader = new BufferedReader(
                    new InputStreamReader(clientSocket.getInputStream(), StandardCharsets.UTF_8)
            );
            var writer = new BufferedWriter(
                    new OutputStreamWriter(clientSocket.getOutputStream(), StandardCharsets.UTF_8)
            );

            // Protocolo de comunicação
            String mensagem;
            while(true) {
                mensagem = reader.readLine();

                System.out.printf("[%s:%d] -> %s\n", enderecoCliente, portaCliente, mensagem);

                writer.write(mensagem.toUpperCase());
                writer.newLine();
                writer.flush();

                if(mensagem.equalsIgnoreCase("SAIR")) break;
            }

            IO.println(".: Sistema encerrado! :.");

            reader.close();
            writer.close();

        } catch (Exception e) {

            System.err.println("Erro: " + e);

        }


        //serverSocket.close(); -- Obrigação de fechar a porta depois de terminada a conexão
    }
}
